# https://cli.netlify.com/netlify-dev/#netlifytoml-dev-block
#제품 모드
[build]
  command = "npm run build" 
  functions = "functions" # 서버리스 함수가 작성된 디렉토리 지정
  publish = "dist" #프로젝트 빌드 결과의 디렉토리

#개발 모드
[dev]
  framework = "#custom" # 감지할 프로젝트 유형. 
  command = "npm run dev:webpack" # 연결할 프로젝트의 개발 서버를 실행하는 명령어
  targetPort = 8079 # 연결할 project 개발 서버의 포트
  port = 8080 # 출력할 netlify 서버의 포트
  publish = "dist" # 프로젝트의 정적 콘텐츠 디렉토리
  autoLaunch = false # 준비되면 자동으로 브라우저를 오픈할 것인지